Repository PRQL/prql, pull requests merged in 2022-10, with the labels that each got.

#1004 build: Upgrade clap to from version 3 to 4
  Cargo.lock
  book/src/main.rs
  prql-compiler/Cargo.toml
Labels: pr-test-all

#1009 ci: Deploy to gh-pages with an artifact
  .github/workflows/publish-web.yaml
Labels: pr-publish-web

#1029 docs: Fix moved dbt url
  book/src/integrations/dbt.md
Labels: pr-test-all

#1051 feat: Add Dockerfile - attempt #2
  .github/actions/build-wheel/action.yaml
  .github/actions/test-rust/action.yaml
  .github/actions/time-compilation/action.yaml
  .github/workflows/publish-web.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/test-all.yaml
  .github/workflows/test-taskfile.yaml
  CHANGELOG.md
  Dockerfile
  README.md
  Taskfile.yml
  USING_DOCKER.md
  book/Cargo.toml
  playground/README.md
  website/README.md
Labels: pr-test-all

#1059 refactor: Remove `context` from resolving
  prql-compiler/src/cli.rs
  prql-compiler/src/lib.rs
  prql-compiler/src/semantic/mod.rs
  prql-compiler/src/semantic/transforms.rs
  prql-compiler/src/sql/translator.rs
Labels: pr-test-all

#1066 ci: Bump nightly pin in cargo-timings GHA
  .github/actions/time-compilation/action.yaml
Labels: pr-cron

#1070 docs: Remove mdbook-admonish from setup-dev
  Taskfile.yml
Labels: pr-test-all

#1095 fix(docs): Change link for Morel
  website/content/faq.md
Labels: pr-test-all
